#!/bin/bash

#SBATCH -J filtros15_9ArrayTFG

#SBATCH -p larga

#SBATCH -o /home/jcorte/TFG/tablas/Ruido15/slurm_output_%A_dir%a.dat

#SBATCH -e /home/jcorte/TFG/tablas/Ruido15/slurm_err_%A_dir%a.dat

#SBATCH --array=0-5

DIR[0]=/home/jcorte/TFG/tablas/Ruido15/consenso/CVCF/
DIR[1]=/home/jcorte/TFG/tablas/Ruido15/consenso/EF/
DIR[2]=/home/jcorte/TFG/tablas/Ruido15/consenso/IPF/
DIR[3]=/home/jcorte/TFG/tablas/Ruido15/maxVotos/CVCF/
DIR[4]=/home/jcorte/TFG/tablas/Ruido15/maxVotos/EF/
DIR[5]=/home/jcorte/TFG/tablas/Ruido15/maxVotos/IPF/

cd ${DIR[$SLURM_ARRAY_TASK_ID]}; python3 menu_9.py