#!/bin/bash

#SBATCH -J filtros5_9ArrayTFG

#SBATCH -p muylarga

#SBATCH -o /home/jcorte/TFG/tablas/Ruido5/slurm_output_%A_dir%a.dat

#SBATCH -e /home/jcorte/TFG/tablas/Ruido5/slurm_err_%A_dir%a.dat

#SBATCH --array=0-3

DIR[0]=/home/jcorte/TFG/tablas/Ruido5/consenso/CVCF/
DIR[1]=/home/jcorte/TFG/tablas/Ruido5/consenso/IPF/
DIR[2]=/home/jcorte/TFG/tablas/Ruido5/maxVotos/CVCF/
DIR[3]=/home/jcorte/TFG/tablas/Ruido5/maxVotos/IPF/

cd ${DIR[$SLURM_ARRAY_TASK_ID]}; python3 menu_9.py