#!/bin/bash

#SBATCH -J filtros15_6ArrayTFG

#SBATCH -p muylarga

#SBATCH -o /home/jcorte/TFG/tablas/Ruido15/slurm_output_%A_dir%a.dat

#SBATCH -e /home/jcorte/TFG/tablas/Ruido15/slurm_err_%A_dir%a.dat

#SBATCH --array=0-1

DIR[0]=/home/jcorte/TFG/tablas/Ruido15/consenso/IPF/
DIR[1]=/home/jcorte/TFG/tablas/Ruido15/maxVotos/IPF/

cd ${DIR[$SLURM_ARRAY_TASK_ID]}; python3 menu_6.py