#!/bin/bash

#SBATCH -J filtros10_2ArrayTFG

#SBATCH -p muylarga

#SBATCH -o /home/jcorte/TFG/tablas/Ruido10/slurm_output_%A_dir%a.dat

#SBATCH -e /home/jcorte/TFG/tablas/Ruido10/slurm_err_%A_dir%a.dat

#SBATCH --array=0-5

DIR[0]=/home/jcorte/TFG/tablas/Ruido10/consenso/CVCF/
DIR[1]=/home/jcorte/TFG/tablas/Ruido10/consenso/EF/
DIR[2]=/home/jcorte/TFG/tablas/Ruido10/consenso/IPF/
DIR[3]=/home/jcorte/TFG/tablas/Ruido10/maxVotos/CVCF/
DIR[4]=/home/jcorte/TFG/tablas/Ruido10/maxVotos/EF/
DIR[5]=/home/jcorte/TFG/tablas/Ruido10/maxVotos/IPF/

cd ${DIR[$SLURM_ARRAY_TASK_ID]}; python3 menu_2.py