#!/bin/bash

#SBATCH -J filtros0_6ArrayTFG

#SBATCH -p muylarga

#SBATCH -o /home/jcorte/TFG/tablas/Ruido0/slurm_output_%A_dir%a.dat

#SBATCH -e /home/jcorte/TFG/tablas/Ruido0/slurm_err_%A_dir%a.dat

#SBATCH --array=0-1

DIR[0]=/home/jcorte/TFG/tablas/Ruido0/maxVotos/IPF/

cd ${DIR[$SLURM_ARRAY_TASK_ID]}; python3 menu_6.py