#!/bin/bash

#SBATCH -J filtros20_9ArrayTFG

#SBATCH -p muylarga

#SBATCH -o /home/jcorte/TFG/tablas/Ruido20/slurm_output_%A_dir%a.dat

#SBATCH -e /home/jcorte/TFG/tablas/Ruido20/slurm_err_%A_dir%a.dat

#SBATCH --array=0-1

DIR[0]=/home/jcorte/TFG/tablas/Ruido20/consenso/CVCF/
DIR[1]=/home/jcorte/TFG/tablas/Ruido20/maxVotos/CVCF/

cd ${DIR[$SLURM_ARRAY_TASK_ID]}; python3 menu_9.py